name: Deploy to Lambda

on:
  push:
    branches: [ master ]          # adjust if needed

permissions:
  id-token: write               # OIDC token
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION || 'us-west-2' }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Package code
        run: |
          python -m pip install -r requirements.txt -t package
          cd package && zip -r ../function.zip . && cd ..
          zip -g function.zip *.py

      - name: Update Lambda code
        run: |
          aws lambda update-function-code \
            --function-name redCouch_LamdaFunction \
            --zip-file fileb://function.zip \
            --region $AWS_REGION
